src/java/BusinessLogic/Controller/HomeController.java
package BusinessLogic.Controller;

import DataAccess.Entity.Home;
import BusinessLogic.Controller.util.JsfUtil;
import BusinessLogic.Controller.util.PaginationHelper;
import DataAccess.DAO.HomeFacade;
import DataAccess.DAO.PersoncollecthomeFacade;
import DataAccess.Entity.Person;
import DataAccess.Entity.Personcollecthome;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "homeController")
@SessionScoped
public class HomeController implements Serializable {

    private Home current;
    private DataModel items = null;
    @EJB
    private DataAccess.DAO.HomeFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private Long idPerson;

    public Long getIdPerson() {
        return idPerson;
    }

    public void setIdPerson(Long idPerson) {
        this.idPerson = idPerson;
    }

    

    public HomeController() {
    }

    public Home getSelected() {
        if (current == null) {
            current = new Home();
            selectedItemIndex = -1;
        }
        return current;
    }

    private HomeFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Home) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }
    
    public String prepareAdd() {
        current = (Home) getItems().getRowData();
        
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Add";
    }
    
    public String prepareCreate() {
        current = new Home();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("HomeCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Home) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("HomeUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Home) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("HomeDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }
    
    public void confirm(Long IdPer){
        
        System.out.println("Estoy en Confirm");
        Personcollecthome relation = new Personcollecthome();
        PersoncollecthomeFacade p = new PersoncollecthomeFacade();
        
        //PersoncollecthomeController controller = new PersoncollecthomeController();
        //controller.getSelected();
        
        System.out.println(IdPer+" User  ****** ");
        System.out.println(current.getIdhome()+" Casa id *********");
        
        relation.setIdhome(current.getIdhome());
        relation.setHometype(current.getHometype());
        
        relation.setIdperson(IdPer);
        
        relation.setCollectionDescription("a");
        relation.setIdcollection(new Long("1"));
        System.out.println(current.getIdhome()+" Casa id *********");
        
        //controller.setCurrent(relation);
        
        //System.out.println(controller.getCurrent().getIdperson());
        
        //controller.create();
        
    }
    
    
    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    
    

    @FacesConverter(forClass = Home.class)
    public static class HomeControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            HomeController controller = (HomeController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "homeController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Home) {
                Home o = (Home) object;
                return getStringKey(o.getIdhome());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Home.class.getName());
            }
        }

    }

}

web/home/Add.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/userProfile.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewHomeTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewHomeLabel_idhome}"/>
                    <h:outputText value="#{homeController.selected.idhome}" title="#{bundle.ViewHomeTitle_idhome}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_city}"/>
                    <h:outputText value="#{homeController.selected.city}" title="#{bundle.ViewHomeTitle_city}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_contracttype}"/>
                    <h:outputText value="#{homeController.selected.contracttype}" title="#{bundle.ViewHomeTitle_contracttype}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_homeaddress}"/>
                    <h:outputText value="#{homeController.selected.homeaddress}" title="#{bundle.ViewHomeTitle_homeaddress}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_hometype}"/>
                    <h:outputText value="#{homeController.selected.hometype}" title="#{bundle.ViewHomeTitle_hometype}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_homevalue}"/>
                    <h:outputText value="#{homeController.selected.homevalue}" title="#{bundle.ViewHomeTitle_homevalue}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_idperson}"/>
                    <h:outputText value="#{homeController.selected.idperson}" title="#{bundle.ViewHomeTitle_idperson}"/>
                </h:panelGrid>
                <br />
                <a href="/servletHomeCollectionAdd">Test</a>
                <h:commandLink action="#{homeController.confirm}" value="Confirm"/>
                
                <h:link outcome="/index" value="#{bundle.ViewHomeIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/home/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/adminProfile.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditHomeTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditHomeLabel_idhome}" for="idhome" />
                    <h:inputText id="idhome" value="#{homeController.selected.idhome}" title="#{bundle.EditHomeTitle_idhome}" required="true" requiredMessage="#{bundle.EditHomeRequiredMessage_idhome}"/>
                    <h:outputLabel value="#{bundle.EditHomeLabel_city}" for="city" />
                    <h:inputText id="city" value="#{homeController.selected.city}" title="#{bundle.EditHomeTitle_city}" />
                    <h:outputLabel value="#{bundle.EditHomeLabel_contracttype}" for="contracttype" />
                    <h:inputText id="contracttype" value="#{homeController.selected.contracttype}" title="#{bundle.EditHomeTitle_contracttype}" />
                    <h:outputLabel value="#{bundle.EditHomeLabel_homeaddress}" for="homeaddress" />
                    <h:inputTextarea rows="4" cols="30" id="homeaddress" value="#{homeController.selected.homeaddress}" title="#{bundle.EditHomeTitle_homeaddress}" />
                    <h:outputLabel value="#{bundle.EditHomeLabel_hometype}" for="hometype" />
                    <h:inputTextarea rows="4" cols="30" id="hometype" value="#{homeController.selected.hometype}" title="#{bundle.EditHomeTitle_hometype}" />
                    <h:outputLabel value="#{bundle.EditHomeLabel_homevalue}" for="homevalue" />
                    <h:inputText id="homevalue" value="#{homeController.selected.homevalue}" title="#{bundle.EditHomeTitle_homevalue}" />
                    <h:outputLabel value="#{bundle.EditHomeLabel_idperson}" for="idperson" />
                    <h:selectOneMenu id="idperson" value="#{homeController.selected.idperson}" title="#{bundle.EditHomeTitle_idperson}" >
                        <f:selectItems value="#{personController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{homeController.update}" value="#{bundle.EditHomeSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditHomeViewLink}"/>
                <br />
                <h:commandLink action="#{homeController.prepareList}" value="#{bundle.EditHomeShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditHomeIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/home/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/userProfile.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListHomeTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListHomeEmpty}" rendered="#{homeController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{homeController.items.rowCount > 0}">
                    <h:outputText value="#{homeController.pagination.pageFirstItem + 1}..#{homeController.pagination.pageLastItem + 1}/#{homeController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{homeController.previous}" value="#{bundle.Previous} #{homeController.pagination.pageSize}" rendered="#{homeController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{homeController.next}" value="#{bundle.Next} #{homeController.pagination.pageSize}" rendered="#{homeController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{homeController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeTitle_idhome}"/>
                            </f:facet>
                            <h:outputText value="#{item.idhome}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeTitle_city}"/>
                            </f:facet>
                            <h:outputText value="#{item.city}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeTitle_contracttype}"/>
                            </f:facet>
                            <h:outputText value="#{item.contracttype}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeTitle_homeaddress}"/>
                            </f:facet>
                            <h:outputText value="#{item.homeaddress}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeTitle_hometype}"/>
                            </f:facet>
                            <h:outputText value="#{item.hometype}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeTitle_homevalue}"/>
                            </f:facet>
                            <h:outputText value="#{item.homevalue}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeTitle_idperson}"/>
                            </f:facet>
                            <h:outputText value="#{item.idperson}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{homeController.prepareAdd}" value="#{bundle.ListHomeAddLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{homeController.prepareView}" value="#{bundle.ListHomeViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{homeController.prepareEdit}" value="#{bundle.ListHomeEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{homeController.destroy}" value="#{bundle.ListHomeDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{homeController.prepareCreate}" value="#{bundle.ListHomeCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListHomeIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/home/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/userProfile.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewHomeTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewHomeLabel_idhome}"/>
                    <h:outputText value="#{homeController.selected.idhome}" title="#{bundle.ViewHomeTitle_idhome}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_city}"/>
                    <h:outputText value="#{homeController.selected.city}" title="#{bundle.ViewHomeTitle_city}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_contracttype}"/>
                    <h:outputText value="#{homeController.selected.contracttype}" title="#{bundle.ViewHomeTitle_contracttype}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_homeaddress}"/>
                    <h:outputText value="#{homeController.selected.homeaddress}" title="#{bundle.ViewHomeTitle_homeaddress}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_hometype}"/>
                    <h:outputText value="#{homeController.selected.hometype}" title="#{bundle.ViewHomeTitle_hometype}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_homevalue}"/>
                    <h:outputText value="#{homeController.selected.homevalue}" title="#{bundle.ViewHomeTitle_homevalue}"/>
                    <h:outputText value="#{bundle.ViewHomeLabel_idperson}"/>
                    <h:outputText value="#{homeController.selected.idperson}" title="#{bundle.ViewHomeTitle_idperson}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{homeController.destroyAndView}" value="#{bundle.ViewHomeDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewHomeEditLink}"/>
                <br />
                <h:commandLink action="#{homeController.prepareCreate}" value="#{bundle.ViewHomeCreateLink}" />
                <br />
                <h:commandLink action="#{homeController.prepareList}" value="#{bundle.ViewHomeShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewHomeIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/home/create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/adminProfile.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateHomeTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateHomeLabel_idhome}" for="idhome" />
                    <h:inputText id="idhome" value="#{homeController.selected.idhome}" title="#{bundle.CreateHomeTitle_idhome}" required="true" requiredMessage="#{bundle.CreateHomeRequiredMessage_idhome}"/>
                    <h:outputLabel value="#{bundle.CreateHomeLabel_city}" for="city" />
                    
                    <h:selectOneMenu   id="city" required="true" value="#{homeController.selected.city}" class="form-control" >
                            
                                                    <f:selectItem itemValue="Bogota" itemLabel="Bogota"/>
                                                    <f:selectItem itemValue="Cali" itemLabel="Cali"/>
                                                    <f:selectItem itemValue="Bucaramanga" itemLabel="Bucaramanga"/>
                    </h:selectOneMenu>
                    
                    <h:outputLabel value="#{bundle.CreateHomeLabel_contracttype}" for="contracttype" />                    
                    <h:selectOneMenu   id="contracttype" required="true" value="#{homeController.selected.contracttype}" class="form-control" >
                                                    <f:selectItem itemValue="Sale" itemLabel="Sale"/>
                                                    <f:selectItem itemValue="Rent" itemLabel="Rent"/>                                
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateHomeLabel_homeaddress}" for="homeaddress" />
                    <h:inputTextarea rows="4" cols="30" id="homeaddress" value="#{homeController.selected.homeaddress}" title="#{bundle.CreateHomeTitle_homeaddress}" />
                    <h:outputLabel value="#{bundle.CreateHomeLabel_hometype}" for="hometype" />
                    
                    <h:selectOneMenu   id="hometype" required="true" value="#{homeController.selected.hometype}" class="form-control" >
                                                    <f:selectItem itemValue="Aprtament" itemLabel="Aprtament"/>
                                                    <f:selectItem itemValue="Home" itemLabel="Home"/>                                
                    </h:selectOneMenu>
                    
                    <h:outputLabel value="#{bundle.CreateHomeLabel_homevalue}" for="homevalue" />
                    <h:inputText id="homevalue" value="#{homeController.selected.homevalue}" title="#{bundle.CreateHomeTitle_homevalue}" />
                    <h:outputLabel value="#{bundle.CreateHomeLabel_idperson}" for="idperson" />
                    <h:selectOneMenu id="idperson" value="#{homeController.selected.idperson}" title="#{bundle.CreateHomeTitle_idperson}" >
                        <f:selectItems value="#{personController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{homeController.create}" value="#{bundle.CreateHomeSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{homeController.prepareList}" value="#{bundle.CreateHomeShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateHomeIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>